version: "3.9"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - mongo-compose-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: bob
      ME_CONFIG_BASICAUTH_PASSWORD: mongo-express
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

    networks:
      - mongo-compose-network
    depends_on:
      - mongo
    restart: unless-stopped

networks:
  mongo-compose-network:
    driver: bridge
