name: Test

# Controls when the workflow will run
on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
      branches: ["master"]
   pull_request:
      branches: ["master"]

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   test_and_build:
      runs-on: ubuntu-latest

      defaults:
         run:
            shell: bash

      steps:
         # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
         - uses: actions/checkout@v3

         - uses: actions/setup-node@v3
           with:
              node-version: 18

         - name: 🔨 Test project
           run: |
              cd backend/
              npm install
              npm test

         - name: Set up QEMU
           uses: docker/setup-qemu-action@v2

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2

         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKER_USER }}
              password: ${{ secrets.DOCKER_PASS }}

         - name: Build and push
           uses: docker/build-push-action@v3
           with:
              context: .
              push: true
              tags: robertoseba/dev:latest
              file: ./Dockerfile

   deploy:
      runs-on: ubuntu-latest
      needs: test_and_build
      environment:
         name: "production"

      steps:
         - name: "Deploy to Azure Web App for Container"
           uses: azure/webapps-deploy@v2
           with:
              app-name: ${{ secrets.AZURE_APP_NAME }}
              publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
              images: https://index.docker.io/v1/robertoseba/dev:latest
